### ISSUE TITLE
Reply to a sad message with a dog picture

### ISSUE THREAD

**Issue by aitorres** [aitorres/dogpicsbot#1]
Right now the bot recognizes certain "triggers" that make it reply with a picture of a dog, such as the word "dog" and a dog emoji.

A cute, new feature for the bot would be to recognize when a message is "sad", e.g. contains a sad emoji, or a sad face `:(`, or the word "sad" (or any other criteria you can come up with), and reply directly to that message with a dog picture, maybe saying "Here's a dog to make you happy!" or something like that.

Briefly:

1. While reading new messages, the bot should recognize when a message is "sad", under any criteria (for example the one mentioned above)
2. If a message is "sad", the bot should reply directly to that mesage (not just send a general message)
3. The reply should have a random dog picture and a cute message such as the one suggested.

**Comment by baspalinckx** [comment]
Could you assign me please? Sounds fun!

**Comment by aitorres** [comment]
@baspalinckx Sure, go ahead!

If you want to live test the bot (`master` branch) on Telegram right now , you can message it at https://t.me/dogpicsbot

**Comment by aitorres** [comment]
Closed by #2.
