### ISSUE TITLE
Follow PEP 8 style guide for variables

### ISSUE THREAD

**Issue by aitorres** [aitorres/dogpicsbot#10]
Generally speaking, the code in `bot.py` does not follow PEP 8's style guide for variables (e.g. variables such as `isSadMessage` and `HELP_MSG` should be in `snake_case`). The code should be updated to follow [PEP 8 naming conventions](https://www.python.org/dev/peps/pep-0008/#naming-conventions).

Bonus: there are some lines that are longer than 100 characters, they should also be reduced to 100 characters or less.

**Comment by seleregb** [comment]
Hi @aitorres I'll like to work on this

**Comment by aitorres** [comment]
Hello @seleregb, sure thing! I am going to assing the issue to you 😄  

Let me know if you have any questions. In any case, if you're going to work on this issue for the Hacktoberfest 2021, I think you should wait until tomorrow to open any PR so that it counts towards the event.

**Comment by seleregb** [comment]
Thanks 😊 . Yeah i'll be waiting till tomorrow lol 😆
